postgres:
  dsn: "host=localhost user=lojes dbname=wechat port=5432 sslmode=disable TimeZone=Asia/Shanghai"
redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""
  connect_timeout: 5000
  pool_size: 30
jwt:
  key: "Z7cK1+zEdxBqrLqt2ul1/ThL4Iyhe4WnYn95WGnlvl+VWZ/1L9HGp2+0cQOzB0le+232dnN7fJH15Zjhdw7Snw=="
  expires_time: 600s
  refresh_time: 604800s